
stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job : BuildJob
        displayName: Build Job 1    
        pool:
          vmImage: 'Ubuntu-20.04'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'
        - script: |
           npm pack
          displayName: 'Package for npm release'
        - task: ArchiveFiles@2
          displayName: 'Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/siddhgurusite.zip
            replaceExistingArchive: true
        - upload: $(Build.ArtifactStagingDirectory)/siddhgurusite.zip
          artifact: drop
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)/siddhgurusite'
            CleanTargetFolder: true
            OverWrite: true
